set_property SRC_FILE_INFO {cfile:/home/parallels/te0711_prj/te0711_prj.srcs/constrs_1/imports/constraints/_i_io.xdc rfile:../../../te0711_prj.srcs/constrs_1/imports/constraints/_i_io.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8 [get_ports {LEDS_tri_o[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports {LEDS_tri_o[1]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {LEDS_tri_o[2]}]
