
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2019.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_JM1_J1_P1A_DEVICE_ID,
		XPAR_JM1_J1_P1A_BASEADDR,
		XPAR_JM1_J1_P1A_INTERRUPT_PRESENT,
		XPAR_JM1_J1_P1A_IS_DUAL
	},
	{
		XPAR_JM1_J1_P1B_DEVICE_ID,
		XPAR_JM1_J1_P1B_BASEADDR,
		XPAR_JM1_J1_P1B_INTERRUPT_PRESENT,
		XPAR_JM1_J1_P1B_IS_DUAL
	},
	{
		XPAR_JM1_J1_P1C_DEVICE_ID,
		XPAR_JM1_J1_P1C_BASEADDR,
		XPAR_JM1_J1_P1C_INTERRUPT_PRESENT,
		XPAR_JM1_J1_P1C_IS_DUAL
	},
	{
		XPAR_JM1_J1_P1D_DEVICE_ID,
		XPAR_JM1_J1_P1D_BASEADDR,
		XPAR_JM1_J1_P1D_INTERRUPT_PRESENT,
		XPAR_JM1_J1_P1D_IS_DUAL
	},
	{
		XPAR_JM2_J2_P2A_DEVICE_ID,
		XPAR_JM2_J2_P2A_BASEADDR,
		XPAR_JM2_J2_P2A_INTERRUPT_PRESENT,
		XPAR_JM2_J2_P2A_IS_DUAL
	},
	{
		XPAR_JM2_J2_P2B_DEVICE_ID,
		XPAR_JM2_J2_P2B_BASEADDR,
		XPAR_JM2_J2_P2B_INTERRUPT_PRESENT,
		XPAR_JM2_J2_P2B_IS_DUAL
	},
	{
		XPAR_JM2_J2_P2C_DEVICE_ID,
		XPAR_JM2_J2_P2C_BASEADDR,
		XPAR_JM2_J2_P2C_INTERRUPT_PRESENT,
		XPAR_JM2_J2_P2C_IS_DUAL
	},
	{
		XPAR_JM3_J3_P3A_DEVICE_ID,
		XPAR_JM3_J3_P3A_BASEADDR,
		XPAR_JM3_J3_P3A_INTERRUPT_PRESENT,
		XPAR_JM3_J3_P3A_IS_DUAL
	},
	{
		XPAR_JM3_J3_P3B_DEVICE_ID,
		XPAR_JM3_J3_P3B_BASEADDR,
		XPAR_JM3_J3_P3B_INTERRUPT_PRESENT,
		XPAR_JM3_J3_P3B_IS_DUAL
	},
	{
		XPAR_MODULE_LEDS_DEVICE_ID,
		XPAR_MODULE_LEDS_BASEADDR,
		XPAR_MODULE_LEDS_INTERRUPT_PRESENT,
		XPAR_MODULE_LEDS_IS_DUAL
	}
};


